name: continuous-integration

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt # visual tests are very finiky so fix the versions
        pip install . # install pyopenms-viz
    - name: Test
      run: |
        python -m pytest --snapshot-warn-unused test/ # do not fail if unused snapshot, just warn
