name: Build and Deploy Documentation

on:
  push:
    branches:
      - main  # Adjust to the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify your desired Python version here

    - name: Install dependencies
      run: |
        pip install -r requirements-test.txt
        pip install sphinx sphinx-gallery sphinx_copybutton # Ensure any necessary packages are installed

    - name: Build documentation
      run: cd docs && sphinx-build -b html ./ ./_build && cd ..

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/ # Path to where the docs are built

